### ISSUE TITLE
General layout

### ISSUE THREAD

**Issue by peteherbst** [fieldmuseum/tailwindfmnh#9]
Add the FMNH layout design to the entire website/repo.

The layout includes:

- Container design for the whole site
- Header (along with logo)
- Footer
- Body layout

**Comment by BlackMG27** [comment]
Okay, I will add a general to tailwindCSS and update the other pages to be inline with the layout.

**Comment by peteherbst** [comment]
Overall, looks good. I just have two changes.

- Page Title:  make it white (not black) and adjust the positioning so it "sits" at the bottom of the blue header. e.g. the [/visit page](https://www.fieldmuseum.org/visit).
- Main Menu: adjust the styles so the links don't shift on hover (see attached video)


https://github.com/fieldmuseum/tailwindfmnh/assets/775699/eb29f671-12a0-4ddc-8a6c-2f9baf9dca6d

**Comment by peteherbst** [comment]
Closed via #13
